name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BEA_KEY: ${{ secrets.BEA_KEY }}
  CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}

jobs:
  prep_pg_docker:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.docker_tag.outputs.value }}      
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-cond@v1
        id: docker_tag
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: ${{ github.head_ref }}
          if_false: main
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          path: db
          registry: docker.pkg.github.com
          repository: covid-projections/can-scrapers/pg
          tags: ${{ steps.docker_tag.outputs.value }}
  test:
    runs-on: ubuntu-latest
    needs: prep_pg_docker
    services:
      postgres:
        image: docker.pkg.github.com/covid-projections/can-scrapers/pg:${{ needs.prep_pg_docker.outputs.docker_tag }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -e .
      - run: black --check ./can_tools
      - name: run tests
        run: pytest .
        env:
          PG_CONN_STR: "postgresql://postgres:postgres@localhost:5432"
